# Generated by Django 6.0.2 on 2026-02-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailverifycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='users/default.jpg', null=True, upload_to='users'),
        ),
    ]
